# Matugen generated colors for Kitty terminal

foreground #e2e2e9
background #121318
selection_foreground #152e60
selection_background #b0c6ff

# Cursor colors
cursor #c0c6dc
cursor_text_color #2a3042

# URL underline color when hovering with mouse
url_color #e0bbdd

# Kitty window border colors and terminal bell
active_border_color #b0c6ff
inactive_border_color #8f9099
bell_border_color #ffb4ab

# Tab bar colors
active_tab_foreground #152e60
active_tab_background #b0c6ff
inactive_tab_foreground #c5c6d0
inactive_tab_background #44464f
tab_bar_background #121318

# The 16 terminal colors
# normal
color0 #121318
color1 #ffb4ab
color2 #c0c6dc
color3 #e0bbdd
color4 #b0c6ff
color5 #2f4578
color6 #404659
color7 #e2e2e9

# bright
color8 #8f9099
color9 #ffb4ab
color10 #c0c6dc
color11 #e0bbdd
color12 #b0c6ff
color13 #2f4578
color14 #404659
color15 #e2e2e9