##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Float lxqt-policykit-agent
windowrule = float, class:^(lxqt-policykit-agent)$

# Float pavucontrol
windowrule = float, class:^(org.pulseaudio.pavucontrol)$
windowrule = size 800 600, class:^(org.pulseaudio.pavucontrol)$

# Float fjordlauncher
windowrule = float, class:^(org.unmojang.FjordLauncher)$
windowrule = size 800 600, class:^(org.unmojang.FjordLauncher)$

# Float PCManFM-Qt file operations (Turkish)
windowrule = float, class:^(pcmanfm-qt)$,title:^(Dosyaları Kopyala)$
windowrule = float, class:^(pcmanfm-qt)$,title:^(Dosyaları Taşı)$
windowrule = float, class:^(pcmanfm-qt)$,title:^(Dosyaları Sil)$
windowrule = size 500 300, class:^(pcmanfm-qt)$,title:^(Dosyaları Kopyala)$
windowrule = size 500 300, class:^(pcmanfm-qt)$,title:^(Dosyaları Taşı)$
windowrule = size 500 300, class:^(pcmanfm-qt)$,title:^(Dosyaları Sil)$

# Float tty-clock
windowrule = float, title:^(tty-clock)$
windowrule = size 600 280, title:^(tty-clock)$
windowrule = center, title:^(tty-clock)$

# Float MPV (IPTV Player)
windowrule = float, class:^(mpv)$
windowrule = size 1280 720, class:^(mpv)$
