# Hyprlock Configuration
# ======================

# Genel ayarlar
general {
    disable_loading_bar = true
    grace = 2
    hide_cursor = true
    no_fade_in = false
}

# Arkaplan
background {
    monitor =
    path = /usr/share/sddm/themes/corners-new/backgrounds/wallhaven-pkogxm.jpg
    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# Şifre giriş kutusu
input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = false
    dots_rounding = -1
    outer_color = rgb(151515)
    inner_color = rgb(200, 200, 200)
    font_color = rgb(10, 10, 10)
    fade_on_empty = true
    fade_timeout = 1000
    placeholder_text = <i>Şifre girin...</i>
    hide_input = false
    rounding = -1
    check_color = rgb(204, 136, 34)
    fail_color = rgb(204, 34, 34)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_timeout = 2000
    fail_transition = 300
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false
    position = 0, -20
    halign = center
    valign = center
}

# Saat
label {
    monitor =
    text = cmd[update:1000] echo "$TIME"
    color = rgba(200, 200, 200, 1.0)
    font_size = 150
    font_family = Quicksand Bold
    position = -100, 120
    halign = right
    valign = bottom
    shadow_passes = 5
    shadow_size = 10
}

# Tarih
label {
    monitor =
    text = cmd[update:18000000] echo "$(date +'%A, %-d %B %Y')"
    color = rgba(200, 200, 200, 1.0)
    font_size = 48
    font_family = Quicksand Bold
    position = -100, 60
    halign = right
    valign = bottom
    shadow_passes = 5
    shadow_size = 10
}

# Kullanıcı adı
label {
    monitor =
    text = Hi there, $USER
    color = rgba(200, 200, 200, 1.0)
    font_size = 24
    font_family = Quicksand Bold
    position = -100, 340
    halign = right
    valign = bottom
    shadow_passes = 5
    shadow_size = 10
}

# Profil resmi
image {
    monitor =
    path = ~/.face
    size = 280
    rounding = -1
    border_size = 4
    border_color = rgb(221, 221, 221)
    rotate = 0
    reload_time = -1
    reload_cmd = 
    position = 0, 200
    halign = center
    valign = center
}