# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Enviroment Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

envd = HYPRCURSOR_SIZE,24
envd = XCURSOR_SIZE,24
envd = QT_CURSOR_SIZE,24
envd = XCURSOR_THEME,capitaine-cursors
envd = HYPRCURSOR_THEME,capitaine-cursors
envd = QT_QPA_PLATFORMTHEME,qt6ct
envd = LIBVA_DRIVER_NAME,nvidia
envd = __GLX_VENDOR_LIBRARY_NAME,nvidia
envd = GBM_BACKEND,nvidia-drm

