# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Input Configuration                    ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Input wiki https://wiki.hyprland.org/Configuring/Variables/#input

input {
    kb_layout = tr
    follow_mouse = 2 # 0|1|2|3
    float_switch_override_focus = 2
}

cursor {
    no_hardware_cursors = false
    default_monitor = 
    zoom_factor = 1.0
    zoom_rigid = false
    enable_hyprcursor = true
    hide_on_key_press = false
    hide_on_touch = true
}

env = XCURSOR_THEME,capitaine-cursors
env = XCURSOR_SIZE,24
