#######################
### BORDERS++ CONFIG ###
#######################

plugin {
    borders-plus-plus {
        add_borders = 1
        col.border_1 = rgb({{colors.primary.default.hex | replace: "#", ""}})
        border_size_1 = -1
        natural_rounding = yes
        
        # Pulse animation
        animate = true
        animation_speed = 2.0
        animation_loop = true
    }
}
