# Matugen generated colors for Hyprland borders

general {
    col.active_border = 0xff{{colors.primary.default.hex | replace: "#", ""}}
    col.inactive_border = 0x80{{colors.outline.default.hex | replace: "#", ""}}
}

decoration {
    shadow {
        color = 0x80{{colors.shadow.default.hex | replace: "#", ""}}
    }
}